import Head from 'next/head';

import { Header } from '@/components/Header';
import { Gallery } from '@/components/Gallery';
import { Footer } from '@/components/Footer';



export default function Home() {
  return (
    <main>
      <Head>
        <title>Photolove</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Gallery />
      <Footer />
    </main>
  );
}
