import Head from 'next/head';
import { Roboto_Mono } from 'next/font/google';

import { Header } from '@/components/Header';
import { Gallery } from '@/components/Gallery';
import { Footer } from '@/components/Footer';

const robotoMono = Roboto_Mono({ subsets: ['latin'] });

export default function Home() {
  return (
    <main className={robotoMono.className}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Gallery />
      <Footer />
    </main>
  );
}
